"""
Django settings for ips_salud_vida project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.utils.translation import gettext_lazy as _


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*^n0#^hky*!t^0byu)d9$4(ff6b6bz=-)p!i#-!sdy=xk*hcfy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [

    'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pacientes',
    'jet.dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ips_salud_vida.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ips_salud_vida.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Cargar variables de entorno desde un archivo .env
load_dotenv()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'America/Bogota'

USE_L10N = True

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

STATIC_ROOT = BASE_DIR / "staticfiles"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JET_CHANGE_FORM_SIBLING_LINKS = True

JET_INDEX_DASHBOARD = 'jet.dashboard.dashboard.DefaultIndexDashboard'

JET_APP_INDEX_DASHBOARD = 'jet.dashboard.dashboard.DefaultAppIndexDashboard'

JET_THEMES = [
    {
        'theme': 'green',
        'color': '#44b78b',
        'title': 'Green'
    },
    {
        'theme': 'light-gray',
        'color': '#222',
        'title': 'Light Gray'
    }
]

JET_DEFAULT_THEME = 'green'

JET_SIDE_MENU_CUSTOM_APPS = []

JET_SIDE_MENU_ITEMS  =  [
        { 'label' :  _ ( 'Tablas' ),  'app_label' :  'core' ,  'items' :  [
        { 'name' : 'pacientes.pais', 'label' : _('Paises') },
        { 'name' : 'pacientes.municipioresidenciahabitual', 'label' : _('Municipios de Residencia') },
        { 'name' : 'pacientes.categoriadiscapacidad', 'label' : _('Categoria Discapacidad') },
        { 'name' : 'pacientes.causamotivoatencion', 'label' : _('Motivos de Atencion') },
        { 'name' : 'pacientes.cie10', 'label' : _('Clasificicacion CIE-10') },
        { 'name' : 'pacientes.comunidad', 'label' : _('Comunidades') },
        { 'name' : 'pacientes.entidadsalud', 'label' : _('Entidad Salud') },
        { 'name' : 'pacientes.enfermedadhuerfana', 'label' : _('Enfermedades Huerfanas') },
        { 'name' : 'pacientes.diagnostico', 'label' : _('Diagnostico') },
        { 'name' : 'pacientes.etnia', 'label' : _('Etnias') },
        { 'name' : 'pacientes.documentovoluntadanticipada', 'label' : _('Documento Voluntad Anticipada') },
        { 'name' : 'pacientes.modalidadservicio', 'label' : _('Modalidad de Servicio') },
        { 'name' : 'pacientes.ocupacion', 'label' : _('Ocupaciones') },
        { 'name' : 'pacientes.oposicionpresunciondonacion', 'label' : _('Oposicion Presuncion de Donacion') },
        { 'name' : 'pacientes.pacientediscapacidad', 'label' : _('Pacientes - Discapacidades') },
        { 'name' : 'pacientes.pacientenacionalidad', 'label' : _('Pacientes - Nacionalidades') },
        { 'name' : 'pacientes.tipodocumento', 'label' : _('Tipo de Documento') },
        { 'name' : 'pacientes.viaingresousuario', 'label' : _('Via Ingreso Usuario') },

    ]},
    { 'label' :  _ ( 'Usuarios' ),  'items' :  [
        { 'name' :  'core.user' },
        { 'name' : 'auth.user' },
        { 'name' :  'auth.group' },
        { 'name' :  'core.userprofile' ,  'permisos' :  [ 'core.user' ]},
    ]},


]
