# Generated by Django 5.2.7 on 2025-10-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='codigo_alfa_3',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
