# Generated by Django 5.2.7 on 2025-10-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_pais_codigo_alfa_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='descripcion',
            field=models.CharField(max_length=60),
        ),
    ]
